In this notebook, I extend the modeling work from the previous notebooks to the day-ahead load forecasting problem. Previously, I forecasted load for a given hour using all available information up to that hour, including the actual temperature for the forecasted hour. However, such high-resolution data is not always available in practice. Day-ahead forecasting introduces additional constraints. First, recent load data are not available; the latest load observations are at least 24 hours old and may be even older, depending on the hour of prediction and the day-ahead market closing time. Second, actual temperature data for the prediction hour are unavailable, and models must rely on weather forecasts, which introduces an additional source of error.

To simulate these conditions, I enforce the following constraints on the test data. Only load lags greater than 24 hours are used as features, and actual temperature is replaced with forecasted temperature. Forecasted temperature is simulated by adding random noise to the actual temperature while incorporating autocorrelation with the forecasted temperature from the previous timestep. To reflect the increasing uncertainty of longer-horizon forecasts, the standard deviation of the noise is scaled linearly with the hour of day, reaching its maximum at hour 24.

This notebook contains the dataset construction and weather forecasting code for the models. This ntoebook also contains the hyperparameter optimzation for the family of models I consider, namely Linear Regression, Ridge Regression, Lasso Regression, XGBoost, and Linear Regression with XGBoost modelled residuals.

In [288]:
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import root_mean_squared_error

import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_squared_error

from itertools import product

In [290]:
df = pd.read_csv("../data/processed/day_ahead_train.csv")

In [292]:
def simulate_long_forecast(actual_temp_series, base_std = 1.0, max_std = 5.0, correlation_factor = 0.5):
    
    simulated_forecast = []
    last_forecast = actual_temp_series.iloc[0]
    
    hours_in_day = 24
    
    for i, actual in enumerate(actual_temp_series):
        hour_of_day = i % hours_in_day
        
        # Scale uncertainty linearly within the day
        hour_std = base_std + (max_std - base_std) * (hour_of_day / (hours_in_day - 1))
        
        # Random error for this hour
        error = np.random.normal(loc = 0, scale = hour_std)
        
        # Forecast combines correlation with last forecast and random error
        new_forecast = last_forecast + correlation_factor * (actual - last_forecast) + error
        
        simulated_forecast.append(new_forecast)
        last_forecast = new_forecast
    
    return pd.Series(simulated_forecast, index = actual_temp_series.index, name = "temp_simulated")

In [55]:
for i in range(10):
    simulated_temp = simulate_long_forecast(df['avg_region_temp']).rename(f"forecast_{i + 1}")
    df = pd.concat([df, simulated_temp], axis = 1)

In [57]:
base_t = 60

for i in range(10):
    df[f"temp_6h_{i + 1}"] = df[f"forecast_{i + 1}"].rolling(6).mean()
    df[f"CDH_{i + 1}"] = (df[f"forecast_{i + 1}"] - base_t).clip(lower=0)
    df[f"HDH_{i + 1}"] = (base_t - df[f"forecast_{i + 1}"]).clip(lower=0) 

df["Load_lag_24h"] = df["Load"].shift(24)
df["Load_lag_48h"] = df["Load"].shift(48)
df["temp_lag_24h"] = df["avg_region_temp"].shift(24)
df = df.dropna()

In [59]:
df

,timestamp,Load,avg_region_temp,forecast_1,forecast_2,forecast_3,forecast_4,forecast_5,forecast_6,forecast_7,...,HDH_8,temp_6h_9,CDH_9,HDH_9,temp_6h_10,CDH_10,HDH_10,Load_lag_24h,Load_lag_48h,temp_lag_24h
6936,2022-10-17 00:00:00,1944,61.880,63.733351,65.604423,64.825909,64.519887,63.137447,67.215771,66.893236,...,0.000000,67.303408,4.371633,0.000000,63.157748,0.000000,1.870279,1980.0,2010.0,63.644
6937,2022-10-17 01:00:00,1894,61.088,62.157563,63.469537,62.084116,61.560210,61.824192,65.242636,63.037355,...,0.000000,65.608777,0.595788,0.000000,62.438415,0.551266,0.000000,1918.0,1942.0,63.572
6938,2022-10-17 02:00:00,1900,60.836,59.692483,61.059373,60.335271,61.560557,62.887374,63.450569,59.579688,...,0.000000,63.340444,0.000000,0.525894,60.538674,0.000000,1.317132,1891.0,1915.0,63.572
6939,2022-10-17 03:00:00,1884,60.692,57.441216,60.010477,61.855902,59.661396,62.143287,62.337104,61.449021,...,0.000000,63.478431,2.089449,0.000000,60.058463,0.540253,0.000000,1860.0,1925.0,63.464
6940,2022-10-17 04:00:00,2004,60.908,58.339865,60.778771,63.338300,61.700214,59.762588,61.331039,61.062843,...,0.000000,62.665716,0.368749,0.000000,58.264090,0.000000,1.880317,1859.0,1929.0,63.932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022-12-31 19:00:00,2434,57.344,53.449449,58.345988,65.478509,62.001984,55.960443,59.749568,56.228505,...,1.162837,59.649564,1.803685,0.000000,57.478225,0.000000,5.483779,2505.0,2556.0,57.056
8756,2022-12-31 20:00:00,2343,57.596,50.674315,53.373343,59.687233,62.070409,63.144591,63.043801,41.636648,...,0.000000,60.132111,1.487658,0.000000,56.789094,0.000000,4.237876,2429.0,2469.0,57.020
8757,2022-12-31 21:00:00,2253,57.596,52.536564,58.123262,59.201525,58.721409,56.354312,60.974494,52.412662,...,0.000000,59.857380,2.478883,0.000000,56.329414,0.000000,4.382497,2332.0,2346.0,56.444
8758,2022-12-31 22:00:00,2159,57.272,53.178901,66.821365,59.371251,57.387179,62.765726,62.077685,56.653463,...,0.534470,58.630876,0.000000,2.069485,56.422488,0.000000,3.663824,2191.0,2189.0,56.516
8759,2022-12-31 23:00:00,2098,57.128,54.741719,66.098411,56.592729,63.382435,56.055038,58.586014,51.858769,...,10.955422,58.029387,0.000000,5.938743,57.537036,3.474521,0.000000,2112.0,2094.0,56.624

In [63]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Load', 'Site-1 Temp', 'Site-2 Temp',
       'Site-3 Temp', 'Site-4 Temp', 'Site-5 Temp', 'Site-1 GHI', 'Site-2 GHI',
       'Site-3 GHI', 'Site-4 GHI', 'Site-5 GHI', 'temp_actual',
       'temp_forecast_1', 'temp_forecast_2', 'temp_forecast_3',
       'temp_forecast_4', 'temp_forecast_5', 'temp_forecast_6',
       'temp_forecast_7', 'temp_forecast_8', 'temp_forecast_9',
       'temp_forecast_10', 'timestamp', 'Hour_sin', 'Hour_cos',
       'temp_6h_actual', 'CDH_actual', 'HDH_actual', 'temp_6h_forecast_1',
       'CDH_forecast_1', 'HDH_forecast_1', 'temp_6h_forecast_2',
       'CDH_forecast_2', 'HDH_forecast_2', 'temp_6h_forecast_3',
       'CDH_forecast_3', 'HDH_forecast_3', 'temp_6h_forecast_4',
       'CDH_forecast_4', 'HDH_forecast_4', 'temp_6h_forecast_5',
       'CDH_forecast_5', 'HDH_forecast_5', 'temp_6h_forecast_6',
       'CDH_forecast_6', 'HDH_forecast_6', 'temp_6h_forecast_7',
       'CDH_forecast_7', 'HDH_forecast_7', 'temp_6h_forecast_8',
       'CDH_forecast_8', 'HDH_forecast_8', 'temp_6h_forecast_9',
       'CDH_forecast_9', 'HDH_forecast_9', 'temp_6h_forecast_10',
       'CDH_forecast_10', 'HDH_forecast_10', 'Load_lag_24h', 'Load_lag_48h',
       'temp_actual_lag_24h', 'is_weekend', 'is_notable_day'],
      dtype='object')

In [65]:
splits_df_loc = "../data/splits/split_bounds.csv"
splits_df = pd.read_csv(splits_df_loc)

def linear_rmse_on_features(df, features_to_train, do_print = False):

    if do_print:
        print("Now training on: ", features_to_train)

    rmse_list = []

    for i in range(1, 9):
        split = f"split_{i}"
    
        row = splits_df[splits_df["split"] == split].iloc[0]
        train_start_date = row["train_start_date"]
        train_end_date = row["train_end_date"]
        val_start_date = row["val_start_date"]
        val_end_date = row["val_end_date"]
    
        train_mask = (df["timestamp"] >= train_start_date) & (df["timestamp"] < train_end_date)
        val_mask = (df["timestamp"] >= val_start_date) & (df["timestamp"] < val_end_date)
        
        train_split = df[train_mask]
        val_split = df[val_mask]
    
        X_train = train_split[features_to_train]
        y_train = train_split["Load"]
    
        X_val = val_split[features_to_train]
        y_val = val_split["Load"]
    
        model = LinearRegression()
        model.fit(X_train, y_train)
    
        y_pred = model.predict(X_val)
        rmse = root_mean_squared_error(y_val, y_pred)
    
        rmse_list.append(rmse)
    if do_print:
        print("RMSEs: ", rmse_list)
        print(f"Average RMSE across splits: {np.mean(rmse_list):.2f} ± {np.std(rmse_list):.2f}\n")
    return np.mean(rmse_list)

def linear_reg_rmse_on_features(df, features_to_train, regression_type = "Lasso", alpha = 0.1, do_print = False):

    if do_print:
        print("Now training on: ", features_to_train)

    rmse_list = []

    for i in range(1, 9):
        split = f"split_{i}"
    
        row = splits_df[splits_df["split"] == split].iloc[0]
        train_start_date = row["train_start_date"]
        train_end_date = row["train_end_date"]
        val_start_date = row["val_start_date"]
        val_end_date = row["val_end_date"]
    
        train_mask = (df["timestamp"] >= train_start_date) & (df["timestamp"] < train_end_date)
        val_mask = (df["timestamp"] >= val_start_date) & (df["timestamp"] < val_end_date)
        
        train_split = df[train_mask]
        val_split = df[val_mask]
    
        X_train = train_split[features_to_train]
        y_train = train_split["Load"]
    
        X_val = val_split[features_to_train]
        y_val = val_split["Load"]

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_val_scaled = scaler.transform(X_val)

        if regression_type == "Lasso":
            model = Lasso(alpha = alpha, max_iter=20_000)

        if regression_type == "Ridge":
            model = Ridge(alpha = alpha, max_iter=20_000)
            
        model.fit(X_train_scaled, y_train)
    
        y_pred = model.predict(X_val_scaled)
        rmse = root_mean_squared_error(y_val, y_pred)
    
        rmse_list.append(rmse)
    if do_print:
        print("RMSEs: ", rmse_list)
        print(f"Average RMSE across splits: {np.mean(rmse_list):.2f} ± {np.std(rmse_list):.2f}\n")
    return np.mean(rmse_list)

In [83]:
features_to_train = ["temp_actual", "temp_6h_actual", "CDH_actual", "HDH_actual", "temp_actual_lag_24h", "Load_lag_24h", "Load_lag_48h", "is_weekend", "is_notable_day"]

print("-"*50)
print(f"Linear Regression")
print("-"*50)

hour_errors = []

for i in range(24):
    
    hour_df = df[df["Hour"] == i]
    hour_errors.append(linear_rmse_on_features(hour_df, features_to_train))

print(f"Max error at hour {np.argmax(hour_errors)}: {np.max(hour_errors)}\n\n")

print("-"*50)
print(f"Lasso Regression")
print("-"*50)

alphas_lasso = np.logspace(-1, 1, 10)
alpha_max_errors = []

for alpha in alphas_lasso:
    print(f"Lasso alpha = {alpha}")
    hour_errors = []
    
    for i in range(24):
        
        hour_df = df[df["Hour"] == i]
        hour_errors.append(linear_reg_rmse_on_features(hour_df, features_to_train, regression_type = "Lasso", alpha = alpha))
        
    print(f"Max error at hour {np.argmax(hour_errors)}: {np.max(hour_errors)}\n\n")
    alpha_max_errors.append(np.max(hour_errors))

print(f"Best performance at worst hour: {np.min(alpha_max_errors)}, alpha = {alphas_lasso[np.argmin(alpha_max_errors)]}\n\n")
    
print("-"*50)
print(f"Ridge Regression")
print("-"*50)

alphas_ridge = np.logspace(-3, 3, 13)
alpha_max_errors = []

for alpha in alphas_ridge:
    print(f"Ridge alpha = {alpha}")
    hour_errors = []
    
    for i in range(24):
        
        hour_df = df[df["Hour"] == i]
        hour_errors.append(linear_reg_rmse_on_features(hour_df, features_to_train, regression_type = "Ridge", alpha = alpha))
        
    print(f"Max error at hour {np.argmax(hour_errors)}: {np.max(hour_errors)}\n\n")
    alpha_max_errors.append(np.max(hour_errors))

print(f"Best performance at worst hour: {np.min(alpha_max_errors)}, alpha = {alphas_ridge[np.argmin(alpha_max_errors)]}\n\n")

--------------------------------------------------
Linear Regression
--------------------------------------------------
Max error at hour 12: 253.06131510514382


--------------------------------------------------
Lasso Regression
--------------------------------------------------
Lasso alpha = 0.1
Max error at hour 12: 253.01632185242892


Lasso alpha = 0.16681005372000587
Max error at hour 12: 252.97600821148524


Lasso alpha = 0.2782559402207124
Max error at hour 12: 252.9126073498234


Lasso alpha = 0.46415888336127786
Max error at hour 12: 252.81177032770776


Lasso alpha = 0.774263682681127
Max error at hour 12: 252.65737722761992


Lasso alpha = 1.291549665014884
Max error at hour 12: 252.43992471688665


Lasso alpha = 2.1544346900318834
Max error at hour 12: 251.8241106439495


Lasso alpha = 3.593813663804626
Max error at hour 12: 251.36608583814268


Lasso alpha = 5.994842503189409
Max error at hour 12: 251.64960870395907


Lasso alpha = 10.0
Max error at hour 12: 252.7839217427346


Best performance at worst hour: 251.36608583814268, alpha = 3.593813663804626


--------------------------------------------------
Ridge Regression
--------------------------------------------------
Ridge alpha = 0.001
Max error at hour 12: 253.06110704099424


Ridge alpha = 0.0031622776601683794
Max error at hour 12: 253.0606572723472


Ridge alpha = 0.01
Max error at hour 12: 253.05923609166234


Ridge alpha = 0.03162277660168379
Max error at hour 12: 253.05475299907926


Ridge alpha = 0.1
Max error at hour 12: 253.040685380573


Ridge alpha = 0.31622776601683794
Max error at hour 12: 252.99724409867247


Ridge alpha = 1.0
Max error at hour 12: 252.8690706241931


Ridge alpha = 3.1622776601683795
Max error at hour 12: 252.53127054156323


Ridge alpha = 10.0
Max error at hour 12: 251.84549601687158


Ridge alpha = 31.622776601683793
Max error at hour 12: 251.30626659056355


Ridge alpha = 100.0
Max error at hour 12: 254.3139673357851


Ridge alpha = 316.22776601683796
Max error at hour 12: 272.63594656570103


Ridge alpha = 1000.0
Max error at hour 13: 326.1553702851398


Best performance at worst hour: 251.30626659056355, alpha = 31.622776601683793

In [85]:
def xgbr_rmse_on_features(df, features_to_train, xgbr_depth = 3, xgbr_estimators = 200, xgbr_lr = 0.1, xgbr_min_child_weight = 5, do_print = False):

    if do_print:
        print("Now training on: ", features_to_train)
    
    rmse_list = []

    for i in range(1, 9):
        split = f"split_{i}"
    
        row = splits_df[splits_df["split"] == split].iloc[0]
        train_start_date = row["train_start_date"]
        train_end_date = row["train_end_date"]
        val_start_date = row["val_start_date"]
        val_end_date = row["val_end_date"]
    
        train_mask = (df["timestamp"] >= train_start_date) & (df["timestamp"] < train_end_date)
        val_mask = (df["timestamp"] >= val_start_date) & (df["timestamp"] < val_end_date)
        
        train_split = df[train_mask].drop(columns=["timestamp"])
        val_split = df[val_mask].drop(columns=["timestamp"])
    
        X_train = df[train_mask][features_to_train]
        y_train = df[train_mask]["Load"]
    
        X_val = df[val_mask][features_to_train]
        y_val = df[val_mask]["Load"]
    
        model = XGBRegressor(objective='reg:squarederror', n_estimators = xgbr_estimators, learning_rate = xgbr_lr, max_depth = xgbr_depth, min_child_weight = xgbr_min_child_weight, subsample=0.8)

        model.fit(X_train, y_train)
    
        y_pred = model.predict(X_val)
        rmse = root_mean_squared_error(y_val, y_pred)
    
        rmse_list.append(rmse)
        
    if do_print:
        print("RMSEs: ", rmse_list)
        print(f"Average RMSE across splits: {np.mean(rmse_list):.2f} ± {np.std(rmse_list):.2f}\n")
    return np.mean(rmse_list)

In [87]:
depths = [i for i in range(2, 5)]
estimators = [i for i in range(50, 300, 50)]
min_child_weight = [10, 20]
lr = [0.05, 0.1]


param_grid = {
    "depth": depths,
    "estimators": estimators,
    "min_child_weight": min_child_weight,
    "lr": lr
}

print("\nHour Depth Est  MCW  LR    RMSE")
print("-" * 40)

xgb_results = []

for hour in range(0, 24):
    for depth, n_est, mcw, lr_ in product(
        param_grid["depth"],
        param_grid["estimators"],
        param_grid["min_child_weight"],
        param_grid["lr"]
    ):
        rmse = xgbr_rmse_on_features(
            df=df[df["Hour"] == hour],
            features_to_train=features_to_train,
            xgbr_depth=depth,
            xgbr_estimators=n_est,
            xgbr_lr=lr_,
            xgbr_min_child_weight=mcw,
            do_print=False
        )
        print(
            f"{hour:02d}   "
            f"{depth:^5} "
            f"{n_est:>3}   "
            f"{mcw:>2}   "
            f"{lr_:>4.2f}  "
            f"{rmse:>8.4f}")
    
        xgb_results.append({
            "hour": hour,
            "max_depth": depth,
            "n_estimators": n_est,
            "min_child_weight": mcw,
            "learning_rate": lr_,
            "mean_rmse": rmse
        })

Hour Depth Est  MCW  LR    RMSE
----------------------------------------
00     2    50   10   0.05   92.9229
00     2    50   10   0.10   85.4627
00     2    50   20   0.05   92.4640
00     2    50   20   0.10   86.7975
00     2   100   10   0.05   85.6027
00     2   100   10   0.10   84.2690
00     2   100   20   0.05   86.3881
00     2   100   20   0.10   85.4843
00     2   150   10   0.05   84.1510
00     2   150   10   0.10   84.2264
00     2   150   20   0.05   85.7448
00     2   150   20   0.10   85.2633
00     2   200   10   0.05   83.9875
00     2   200   10   0.10   83.7975
00     2   200   20   0.05   85.3353
00     2   200   20   0.10   85.2964
00     2   250   10   0.05   83.8796
00     2   250   10   0.10   83.6221
00     2   250   20   0.05   85.4271
00     2   250   20   0.10   85.3829
00     3    50   10   0.05   91.0417
00     3    50   10   0.10   84.6575
00     3    50   20   0.05   90.3996
00     3    50   20   0.10   86.0190
00     3   100   10   0.05   84.8625
00     3   100   10   0.10   84.1122
00     3   100   20   0.05   85.9577
00     3   100   20   0.10   85.7736
00     3   150   10   0.05   84.0349
00     3   150   10   0.10   84.7884
00     3   150   20   0.05   85.6167
00     3   150   20   0.10   85.6833
00     3   200   10   0.05   84.1401
00     3   200   10   0.10   84.6991
00     3   200   20   0.05   85.3871
00     3   200   20   0.10   86.0094
00     3   250   10   0.05   83.9942
00     3   250   10   0.10   84.9084
00     3   250   20   0.05   85.3153
00     3   250   20   0.10   86.2061
00     4    50   10   0.05   90.3906
00     4    50   10   0.10   85.4333
00     4    50   20   0.05   90.4448
00     4    50   20   0.10   86.5537
00     4   100   10   0.05   84.9023
00     4   100   10   0.10   85.2098
00     4   100   20   0.05   86.2548
00     4   100   20   0.10   86.6403
00     4   150   10   0.05   84.4280
00     4   150   10   0.10   85.6681
00     4   150   20   0.05   85.9667
00     4   150   20   0.10   86.8610
00     4   200   10   0.05   84.5524
00     4   200   10   0.10   86.2920
00     4   200   20   0.05   85.8860
00     4   200   20   0.10   87.7146
00     4   250   10   0.05   84.5580
00     4   250   10   0.10   86.1272
00     4   250   20   0.05   86.1298
00     4   250   20   0.10   88.1201
01     2    50   10   0.05   95.9430
01     2    50   10   0.10   88.0460
01     2    50   20   0.05   94.8623
01     2    50   20   0.10   88.7165
01     2   100   10   0.05   88.5142
01     2   100   10   0.10   86.5767
01     2   100   20   0.05   88.1513
01     2   100   20   0.10   87.4748
01     2   150   10   0.05   87.4943
01     2   150   10   0.10   86.5115
01     2   150   20   0.05   87.3285
01     2   150   20   0.10   87.4530
01     2   200   10   0.05   87.0240
01     2   200   10   0.10   86.6718
01     2   200   20   0.05   86.7458
01     2   200   20   0.10   87.2245
01     2   250   10   0.05   86.5287
01     2   250   10   0.10   86.5912
01     2   250   20   0.05   86.4377
01     2   250   20   0.10   87.2336
01     3    50   10   0.05   93.0079
01     3    50   10   0.10   87.0830
01     3    50   20   0.05   92.3622
01     3    50   20   0.10   87.5956
01     3   100   10   0.05   87.4331
01     3   100   10   0.10   86.2689
01     3   100   20   0.05   87.6555
01     3   100   20   0.10   86.5872
01     3   150   10   0.05   86.6270
01     3   150   10   0.10   86.5690
01     3   150   20   0.05   87.1632
01     3   150   20   0.10   87.6044
01     3   200   10   0.05   86.5867
01     3   200   10   0.10   86.8952
01     3   200   20   0.05   86.8823
01     3   200   20   0.10   87.8281
01     3   250   10   0.05   86.5072
01     3   250   10   0.10   86.8758
01     3   250   20   0.05   86.8660
01     3   250   20   0.10   88.0080
01     4    50   10   0.05   92.5721
01     4    50   10   0.10   87.3980
01     4    50   20   0.05   91.9575
01     4    50   20   0.10   87.8724
01     4   100   10   0.05   87.2761
01     4   100   10   0.10   86.9710
01     4   100   20   0.05   87.7402
01     4   100   20   0.10   87.0519
01     4   150   10   0.05   87.2018
01     4   150   10   0.10   87.5090
01     4   150   20   0.05   87.4300
01     4   150   20   0.10   87.9302
01     4   200   10   0.05   86.9706
01     4   200   10   0.10   87.5691
01     4   200   20   0.05   87.3504
01     4   200   20   0.10   88.0706
01     4   250   10   0.05   86.6096
01     4   250   10   0.10   87.7991
01     4   250   20   0.05   87.3945
01     4   250   20   0.10   88.4514
02     2    50   10   0.05   88.0703
02     2    50   10   0.10   80.4560
02     2    50   20   0.05   87.4229
02     2    50   20   0.10   81.7024
02     2   100   10   0.05   80.4285
02     2   100   10   0.10   78.1358
02     2   100   20   0.05   80.8245
02     2   100   20   0.10   79.6691
02     2   150   10   0.05   79.3215
02     2   150   10   0.10   78.1303
02     2   150   20   0.05   79.8661
02     2   150   20   0.10   79.3777
02     2   200   10   0.05   78.5518
02     2   200   10   0.10   78.1706
02     2   200   20   0.05   79.1603
02     2   200   20   0.10   79.1542
02     2   250   10   0.05   78.3952
02     2   250   10   0.10   77.9282
02     2   250   20   0.05   79.0577
02     2   250   20   0.10   79.1167
02     3    50   10   0.05   84.9352
02     3    50   10   0.10   78.9708
02     3    50   20   0.05   84.6692
02     3    50   20   0.10   80.2797
02     3   100   10   0.05   79.5941
02     3   100   10   0.10   78.0164
02     3   100   20   0.05   79.9335
02     3   100   20   0.10   78.9957
02     3   150   10   0.05   78.8642
02     3   150   10   0.10   78.4133
02     3   150   20   0.05   79.4481
02     3   150   20   0.10   79.6320
02     3   200   10   0.05   78.5460
02     3   200   10   0.10   78.6297
02     3   200   20   0.05   79.2737
02     3   200   20   0.10   79.9559
02     3   250   10   0.05   78.4013
02     3   250   10   0.10   78.6894
02     3   250   20   0.05   79.3835
02     3   250   20   0.10   80.0155
02     4    50   10   0.05   84.4555
02     4    50   10   0.10   80.1328
02     4    50   20   0.05   83.7097
02     4    50   20   0.10   80.6038
02     4   100   10   0.05   79.5145
02     4   100   10   0.10   79.4971
02     4   100   20   0.05   79.9748
02     4   100   20   0.10   79.8310
02     4   150   10   0.05   79.3109
02     4   150   10   0.10   80.2101
02     4   150   20   0.05   79.8108
02     4   150   20   0.10   80.7053
02     4   200   10   0.05   78.9859
02     4   200   10   0.10   80.2857
02     4   200   20   0.05   79.7189
02     4   200   20   0.10   81.2195
02     4   250   10   0.05   78.7903
02     4   250   10   0.10   80.1491
02     4   250   20   0.05   79.8012
02     4   250   20   0.10   81.4359
03     2    50   10   0.05   85.5470
03     2    50   10   0.10   77.5219
03     2    50   20   0.05   84.1488
03     2    50   20   0.10   77.3570
03     2   100   10   0.05   76.8753
03     2   100   10   0.10   75.5604
03     2   100   20   0.05   76.6868
03     2   100   20   0.10   75.7198
03     2   150   10   0.05   75.5657
03     2   150   10   0.10   75.7572
03     2   150   20   0.05   75.1682
03     2   150   20   0.10   75.5031
03     2   200   10   0.05   75.1131
03     2   200   10   0.10   75.7612
03     2   200   20   0.05   74.9612
03     2   200   20   0.10   75.5631
03     2   250   10   0.05   75.2473
03     2   250   10   0.10   75.6923
03     2   250   20   0.05   74.8814
03     2   250   20   0.10   75.3817
03     3    50   10   0.05   81.1606
03     3    50   10   0.10   75.9005
03     3    50   20   0.05   80.1291
03     3    50   20   0.10   76.6396
03     3   100   10   0.05   76.1205
03     3   100   10   0.10   75.4961
03     3   100   20   0.05   75.5969
03     3   100   20   0.10   75.7956
03     3   150   10   0.05   75.6301
03     3   150   10   0.10   75.9881
03     3   150   20   0.05   75.1321
03     3   150   20   0.10   76.1271
03     3   200   10   0.05   75.5693
03     3   200   10   0.10   76.2936
03     3   200   20   0.05   75.2177
03     3   200   20   0.10   76.0770
03     3   250   10   0.05   75.6595
03     3   250   10   0.10   76.1158
03     3   250   20   0.05   75.1838
03     3   250   20   0.10   76.0810
03     4    50   10   0.05   80.3918
03     4    50   10   0.10   76.7929
03     4    50   20   0.05   79.2277
03     4    50   20   0.10   76.0384
03     4   100   10   0.05   76.2903
03     4   100   10   0.10   76.4035
03     4   100   20   0.05   75.5615
03     4   100   20   0.10   75.4883
03     4   150   10   0.05   76.1320
03     4   150   10   0.10   76.9784
03     4   150   20   0.05   75.3263
03     4   150   20   0.10   76.0110
03     4   200   10   0.05   76.2614
03     4   200   10   0.10   77.2646
03     4   200   20   0.05   75.4323
03     4   200   20   0.10   76.4149
03     4   250   10   0.05   76.2993
03     4   250   10   0.10   77.4229
03     4   250   20   0.05   75.5734
03     4   250   20   0.10   76.3497
04     2    50   10   0.05   88.5517
04     2    50   10   0.10   81.2823
04     2    50   20   0.05   88.5242
04     2    50   20   0.10   80.2360
04     2   100   10   0.05   80.2367
04     2   100   10   0.10   79.1602
04     2   100   20   0.05   80.2201
04     2   100   20   0.10   78.5782
04     2   150   10   0.05   79.0262
04     2   150   10   0.10   79.3580
04     2   150   20   0.05   78.9469
04     2   150   20   0.10   78.8065
04     2   200   10   0.05   78.6609
04     2   200   10   0.10   79.5447
04     2   200   20   0.05   78.7689
04     2   200   20   0.10   78.8502
04     2   250   10   0.05   78.8051
04     2   250   10   0.10   79.9562
04     2   250   20   0.05   78.6920
04     2   250   20   0.10   78.7971
04     3    50   10   0.05   83.6608
04     3    50   10   0.10   79.0976
04     3    50   20   0.05   82.6447
04     3    50   20   0.10   78.5633
04     3   100   10   0.05   78.5451
04     3   100   10   0.10   78.9469
04     3   100   20   0.05   78.1460
04     3   100   20   0.10   78.1575
04     3   150   10   0.05   78.1276
04     3   150   10   0.10   79.4309
04     3   150   20   0.05   77.6672
04     3   150   20   0.10   78.6261
04     3   200   10   0.05   78.2470
04     3   200   10   0.10   80.2564
04     3   200   20   0.05   77.8195
04     3   200   20   0.10   78.8555
04     3   250   10   0.05   78.5152
04     3   250   10   0.10   80.4544
04     3   250   20   0.05   77.9212
04     3   250   20   0.10   79.0903
04     4    50   10   0.05   81.5046
04     4    50   10   0.10   78.7346
04     4    50   20   0.05   81.4967
04     4    50   20   0.10   77.3503
04     4   100   10   0.05   77.7207
04     4   100   10   0.10   78.6025
04     4   100   20   0.05   77.5279
04     4   100   20   0.10   77.3729
04     4   150   10   0.05   77.8568
04     4   150   10   0.10   79.1173
04     4   150   20   0.05   77.6290
04     4   150   20   0.10   77.9463
04     4   200   10   0.05   78.2397
04     4   200   10   0.10   79.8196
04     4   200   20   0.05   77.9035
04     4   200   20   0.10   78.3518
04     4   250   10   0.05   78.4581
04     4   250   10   0.10   80.0650
04     4   250   20   0.05   78.1418
04     4   250   20   0.10   78.4910
05     2    50   10   0.05  108.5589
05     2    50   10   0.10   98.2149
05     2    50   20   0.05  107.8226
05     2    50   20   0.10   99.2179
05     2   100   10   0.05   98.2481
05     2   100   10   0.10   95.1357
05     2   100   20   0.05   98.5500
05     2   100   20   0.10   97.2834
05     2   150   10   0.05   96.3477
05     2   150   10   0.10   95.7908
05     2   150   20   0.05   97.0166
05     2   150   20   0.10   97.5103
05     2   200   10   0.05   95.7930
05     2   200   10   0.10   96.4076
05     2   200   20   0.05   96.4550
05     2   200   20   0.10   97.7198
05     2   250   10   0.05   95.5158
05     2   250   10   0.10   96.1044
05     2   250   20   0.05   96.4872
05     2   250   20   0.10   97.4850
05     3    50   10   0.05  100.4557
05     3    50   10   0.10   94.5082
05     3    50   20   0.05  100.5228
05     3    50   20   0.10   95.3370
05     3   100   10   0.05   94.5260
05     3   100   10   0.10   93.5850
05     3   100   20   0.05   95.6719
05     3   100   20   0.10   95.1906
05     3   150   10   0.05   94.1521
05     3   150   10   0.10   94.4160
05     3   150   20   0.05   95.2267
05     3   150   20   0.10   95.5267
05     3   200   10   0.05   94.3786
05     3   200   10   0.10   95.0138
05     3   200   20   0.05   95.0894
05     3   200   20   0.10   95.9907
05     3   250   10   0.05   94.6546
05     3   250   10   0.10   95.4045
05     3   250   20   0.05   95.1126
05     3   250   20   0.10   96.2400
05     4    50   10   0.05   97.4416
05     4    50   10   0.10   93.4493
05     4    50   20   0.05   98.3386
05     4    50   20   0.10   94.8199
05     4   100   10   0.05   93.5124
05     4   100   10   0.10   94.1678
05     4   100   20   0.05   94.2308
05     4   100   20   0.10   95.1268
05     4   150   10   0.05   94.1098
05     4   150   10   0.10   95.2643
05     4   150   20   0.05   94.4449
05     4   150   20   0.10   95.6943
05     4   200   10   0.05   94.6365
05     4   200   10   0.10   96.2134
05     4   200   20   0.05   94.6743
05     4   200   20   0.10   96.2529
05     4   250   10   0.05   95.0939
05     4   250   10   0.10   96.8066
05     4   250   20   0.05   95.0199
05     4   250   20   0.10   96.7145
06     2    50   10   0.05  135.8203
06     2    50   10   0.10  124.3344
06     2    50   20   0.05  134.4051
06     2    50   20   0.10  124.0242
06     2   100   10   0.05  124.0016
06     2   100   10   0.10  122.5111
06     2   100   20   0.05  124.1854
06     2   100   20   0.10  122.7402
06     2   150   10   0.05  123.1121
06     2   150   10   0.10  123.3952
06     2   150   20   0.05  123.3372
06     2   150   20   0.10  123.4069
06     2   200   10   0.05  122.4279
06     2   200   10   0.10  123.7225
06     2   200   20   0.05  123.4439
06     2   200   20   0.10  124.5731
06     2   250   10   0.05  122.7292
06     2   250   10   0.10  124.6686
06     2   250   20   0.05  124.0101
06     2   250   20   0.10  125.4774
06     3    50   10   0.05  126.8480
06     3    50   10   0.10  122.6089
06     3    50   20   0.05  126.2863
06     3    50   20   0.10  123.7894
06     3   100   10   0.05  122.1463
06     3   100   10   0.10  123.0404
06     3   100   20   0.05  122.5486
06     3   100   20   0.10  125.2540
06     3   150   10   0.05  122.9379
06     3   150   10   0.10  124.4800
06     3   150   20   0.05  123.4193
06     3   150   20   0.10  127.0052
06     3   200   10   0.05  123.4164
06     3   200   10   0.10  125.2622
06     3   200   20   0.05  124.1702
06     3   200   20   0.10  128.3189
06     3   250   10   0.05  123.9095
06     3   250   10   0.10  126.3725
06     3   250   20   0.05  124.9908
06     3   250   20   0.10  128.7391
06     4    50   10   0.05  123.5115
06     4    50   10   0.10  121.3122
06     4    50   20   0.05  124.3707
06     4    50   20   0.10  122.9955
06     4   100   10   0.05  120.6487
06     4   100   10   0.10  122.9145
06     4   100   20   0.05  122.3412
06     4   100   20   0.10  125.2722
06     4   150   10   0.05  121.8908
06     4   150   10   0.10  124.7875
06     4   150   20   0.05  123.5620
06     4   150   20   0.10  126.8263
06     4   200   10   0.05  122.7741
06     4   200   10   0.10  125.8311
06     4   200   20   0.05  124.5881
06     4   200   20   0.10  127.6723
06     4   250   10   0.05  123.6971
06     4   250   10   0.10  126.8473
06     4   250   20   0.05  125.3852
06     4   250   20   0.10  128.7748
07     2    50   10   0.05  173.2518
07     2    50   10   0.10  159.9505
07     2    50   20   0.05  172.5610
07     2    50   20   0.10  159.1561
07     2   100   10   0.05  159.0043
07     2   100   10   0.10  156.4456
07     2   100   20   0.05  159.4372
07     2   100   20   0.10  155.6818
07     2   150   10   0.05  156.9727
07     2   150   10   0.10  155.7312
07     2   150   20   0.05  157.0036
07     2   150   20   0.10  154.7245
07     2   200   10   0.05  155.5697
07     2   200   10   0.10  155.5775
07     2   200   20   0.05  155.8444
07     2   200   20   0.10  154.6668
07     2   250   10   0.05  155.4030
07     2   250   10   0.10  155.6259
07     2   250   20   0.05  155.3408
07     2   250   20   0.10  155.1474
07     3    50   10   0.05  163.9618
07     3    50   10   0.10  157.5376
07     3    50   20   0.05  162.6112
07     3    50   20   0.10  156.2422
07     3   100   10   0.05  156.5186
07     3   100   10   0.10  155.7234
07     3   100   20   0.05  156.1581
07     3   100   20   0.10  154.7265
07     3   150   10   0.05  155.8073
07     3   150   10   0.10  156.9509
07     3   150   20   0.05  154.6990
07     3   150   20   0.10  156.4471
07     3   200   10   0.05  155.0285
07     3   200   10   0.10  158.0534
07     3   200   20   0.05  154.5925
07     3   200   20   0.10  157.3544
07     3   250   10   0.05  155.1409
07     3   250   10   0.10  159.1654
07     3   250   20   0.05  155.0876
07     3   250   20   0.10  158.0681
07     4    50   10   0.05  160.7798
07     4    50   10   0.10  156.1811
07     4    50   20   0.05  160.4012
07     4    50   20   0.10  155.4373
07     4   100   10   0.05  155.8515
07     4   100   10   0.10  156.7564
07     4   100   20   0.05  155.8001
07     4   100   20   0.10  156.2318
07     4   150   10   0.05  155.5723
07     4   150   10   0.10  158.9259
07     4   150   20   0.05  155.1984
07     4   150   20   0.10  158.2492
07     4   200   10   0.05  156.3111
07     4   200   10   0.10  160.5086
07     4   200   20   0.05  155.7745
07     4   200   20   0.10  160.1096
07     4   250   10   0.05  157.2018
07     4   250   10   0.10  161.9371
07     4   250   20   0.05  156.6632
07     4   250   20   0.10  161.2770
08     2    50   10   0.05  202.1973
08     2    50   10   0.10  188.7175
08     2    50   20   0.05  200.4346
08     2    50   20   0.10  188.9610
08     2   100   10   0.05  189.0126
08     2   100   10   0.10  182.7620
08     2   100   20   0.05  189.1262
08     2   100   20   0.10  184.5138
08     2   150   10   0.05  185.1473
08     2   150   10   0.10  182.1137
08     2   150   20   0.05  185.6087
08     2   150   20   0.10  183.3522
08     2   200   10   0.05  184.1375
08     2   200   10   0.10  182.1530
08     2   200   20   0.05  183.8218
08     2   200   20   0.10  182.8565
08     2   250   10   0.05  183.9347
08     2   250   10   0.10  183.0585
08     2   250   20   0.05  183.6365
08     2   250   20   0.10  183.6204
08     3    50   10   0.05  194.1971
08     3    50   10   0.10  185.4353
08     3    50   20   0.05  193.9436
08     3    50   20   0.10  185.7674
08     3   100   10   0.05  185.7278
08     3   100   10   0.10  183.1834
08     3   100   20   0.05  185.6657
08     3   100   20   0.10  184.0806
08     3   150   10   0.05  184.0194
08     3   150   10   0.10  183.8870
08     3   150   20   0.05  184.2904
08     3   150   20   0.10  184.3073
08     3   200   10   0.05  183.7637
08     3   200   10   0.10  184.9776
08     3   200   20   0.05  184.0995
08     3   200   20   0.10  185.1464
08     3   250   10   0.05  184.0214
08     3   250   10   0.10  186.6965
08     3   250   20   0.05  184.2372
08     3   250   20   0.10  186.3497
08     4    50   10   0.05  191.6009
08     4    50   10   0.10  185.1775
08     4    50   20   0.05  191.7620
08     4    50   20   0.10  183.5566
08     4   100   10   0.05  184.7485
08     4   100   10   0.10  184.8293
08     4   100   20   0.05  184.0099
08     4   100   20   0.10  183.8272
08     4   150   10   0.05  183.7104
08     4   150   10   0.10  187.5601
08     4   150   20   0.05  183.5664
08     4   150   20   0.10  186.3855
08     4   200   10   0.05  183.7103
08     4   200   10   0.10  188.4121
08     4   200   20   0.05  183.7751
08     4   200   20   0.10  187.7695
08     4   250   10   0.05  184.8200
08     4   250   10   0.10  190.0152

In [91]:
xgb_results_df = pd.DataFrame(xgb_results)

rmse_by_hour = xgb_results_df.pivot_table(
    index=["max_depth", "n_estimators", "min_child_weight", "learning_rate"],
    columns="hour",
    values="mean_rmse"
).reset_index()

best_per_hour_xgb = xgb_results_df.loc[xgb_results_df.groupby("hour")["mean_rmse"].idxmin()].reset_index(drop=True)

In [95]:
best_per_hour_xgb

    hour  max_depth  n_estimators  min_child_weight  learning_rate   mean_rmse
0      0          2           250                10           0.10   83.622075
1      1          3           100                10           0.10   86.268905
2      2          2           250                10           0.10   77.928198
3      3          2           250                20           0.05   74.881408
4      4          4            50                20           0.10   77.350257
5      5          4            50                10           0.10   93.449283
6      6          4           100                10           0.05  120.648700
7      7          3           200                20           0.05  154.592488
8      8          2           150                10           0.10  182.113663
9      9          4           100                10           0.05  206.955672
10    10          2           250                10           0.05  213.390164
11    11          2           250                10           0.05  221.790038
12    12          3           100                10           0.10  225.953939
13    13          2           250                10           0.10  218.013270
14    14          2           250                10           0.05  211.524858
15    15          3           250                10           0.05  184.393017
16    16          2           250                10           0.05  153.788250
17    17          3           150                10           0.10  130.216883
18    18          3           250                10           0.05  115.848450
19    19          3           100                10           0.10  108.068946
20    20          3           250                10           0.10   97.087445
21    21          2           250                10           0.10   84.256008
22    22          4           150                10           0.10   79.492652
23    23          2           250                10           0.10   81.274401

In [121]:
best_per_hour_hyperparams = best_per_hour_xgb[["max_depth", "n_estimators", "min_child_weight", "learning_rate"]]
best_at_max_hour_hyperparams = best_per_hour_xgb.loc[best_per_hour_xgb["mean_rmse"].idxmax()].to_frame().T

best_per_hour_hyperparams.to_csv("../src/models/best_per_hour_xgb_hyperparams.csv", index=False)
best_at_max_hour_hyperparams.to_csv("../src/models/best_max_hour_xgb_hyperparams.csv", index=False)

In [113]:
def linear_xgbr_rmse_on_features(df, features_to_train, xgbr_depth = 3, xgbr_estimators = 200, xgbr_lr = 0.1, xgbr_min_child_weight = 5, do_print = False):

    if do_print:
        print("Now training on: ", features_to_train)

    rmse_list = []
    df = df.sort_values(by=["timestamp"])

    for i in range(1, 9):
        split = f"split_{i}"
    
        row = splits_df[splits_df["split"] == split].iloc[0]
        train_start_date = row["train_start_date"]
        train_end_date = row["train_end_date"]
        val_start_date = row["val_start_date"]
        val_end_date = row["val_end_date"]
    
        train_mask = (df["timestamp"] >= train_start_date) & (df["timestamp"] < train_end_date)
        val_mask = (df["timestamp"] >= val_start_date) & (df["timestamp"] < val_end_date)
        
        train_split = df[train_mask].drop(columns=["timestamp", "Load"])
        val_split = df[val_mask].drop(columns=["timestamp", "Load"])
    
        X_train = train_split[features_to_train]
        y_train = df[train_mask]["Load"]
    
        X_val = val_split[features_to_train]
        y_val = df[val_mask]["Load"]

        n_train_samples = len(X_train)
        initial_len = int(0.6 * n_train_samples)
        step_size = 24

        oos_residuals = np.full(n_train_samples, np.nan)

        for start in range(initial_len, n_train_samples, step_size):
            end = min(start + step_size, n_train_samples)

            wf_lin = LinearRegression()
            wf_lin.fit(X_train.iloc[:start], y_train.iloc[:start])
        
            preds = wf_lin.predict(X_train.iloc[start:end])

            oos_residuals[start:end] = y_train.iloc[start:end] - preds

        mask = ~np.isnan(oos_residuals)

        xgbr = XGBRegressor(objective='reg:squarederror', n_estimators = xgbr_estimators, learning_rate=xgbr_lr, max_depth = xgbr_depth, min_child_weight = xgbr_min_child_weight, subsample=0.8, random_state=12)
        xgbr.fit(train_split.iloc[mask], oos_residuals[mask])

        model = LinearRegression()
        model.fit(X_train, y_train)
    
        y_lin_pred = model.predict(X_val)
        y_xgbr_pred = xgbr.predict(val_split)
        rmse = root_mean_squared_error(y_val, y_lin_pred + y_xgbr_pred)
    
        rmse_list.append(rmse)

    if do_print:
        print("RMSEs: ", rmse_list)
        print(f"Average RMSE across splits: {np.mean(rmse_list):.2f} ± {np.std(rmse_list):.2f}\n")
        
    return np.mean(rmse_list)

In [119]:
features_to_train = ["temp_actual", "temp_6h_actual", "CDH_actual", "HDH_actual", "temp_actual_lag_24h", "Load_lag_24h", "Load_lag_48h", "is_weekend", "is_notable_day"]


depths = [i for i in range(2, 5)]
estimators = [i for i in range(50, 300, 50)]
min_child_weight = [10, 20]
lr = [0.05, 0.1]


param_grid = {
    "depth": depths,
    "estimators": estimators,
    "min_child_weight": min_child_weight,
    "lr": lr
}

print("\nHour Depth Est  MCW  LR    RMSE")
print("-" * 40)

lin_xgb_results = []

for hour in range(0, 24):
    for depth, n_est, mcw, lr_ in product(
        param_grid["depth"],
        param_grid["estimators"],
        param_grid["min_child_weight"],
        param_grid["lr"]
    ):

        rmse = linear_xgbr_rmse_on_features(
            df=df[df["Hour"] == hour],
            features_to_train=features_to_train,
            xgbr_depth=depth,
            xgbr_estimators=n_est,
            xgbr_lr=lr_,
            xgbr_min_child_weight=mcw,
            do_print=False
        )
        print(
            f"{hour:02d}   "
            f"{depth:^5} "
            f"{n_est:>3}   "
            f"{mcw:>2}   "
            f"{lr_:>4.2f}  "
            f"{rmse:>8.4f}")
    
        lin_xgb_results.append({
            "hour": hour,
            "max_depth": depth,
            "n_estimators": n_est,
            "min_child_weight": mcw,
            "learning_rate": lr_,
            "mean_rmse": rmse
        })

Hour Depth Est  MCW  LR    RMSE
----------------------------------------
00     2    50   10   0.05   74.3290
00     2    50   10   0.10   75.3166
00     2    50   20   0.05   75.4180
00     2    50   20   0.10   76.4439
00     2   100   10   0.05   75.2162
00     2   100   10   0.10   76.7734
00     2   100   20   0.05   76.3464
00     2   100   20   0.10   78.0928
00     2   150   10   0.05   76.3183
00     2   150   10   0.10   78.7754
00     2   150   20   0.05   76.9917
00     2   150   20   0.10   79.6367
00     2   200   10   0.05   77.3581
00     2   200   10   0.10   80.0924
00     2   200   20   0.05   77.5587
00     2   200   20   0.10   80.4906
00     2   250   10   0.05   77.8115
00     2   250   10   0.10   80.3573
00     2   250   20   0.05   78.1361
00     2   250   20   0.10   80.8711
00     3    50   10   0.05   74.4392
00     3    50   10   0.10   75.7957
00     3    50   20   0.05   75.6153
00     3    50   20   0.10   76.0583
00     3   100   10   0.05   76.0517
00     3   100   10   0.10   78.2755
00     3   100   20   0.05   76.3621
00     3   100   20   0.10   78.0892
00     3   150   10   0.05   77.6740
00     3   150   10   0.10   79.5222
00     3   150   20   0.05   77.2147
00     3   150   20   0.10   79.4823
00     3   200   10   0.05   78.5642
00     3   200   10   0.10   79.9988
00     3   200   20   0.05   78.0012
00     3   200   20   0.10   80.4318
00     3   250   10   0.05   78.8367
00     3   250   10   0.10   80.0825
00     3   250   20   0.05   78.5917
00     3   250   20   0.10   81.0127
00     4    50   10   0.05   74.2393
00     4    50   10   0.10   76.6380
00     4    50   20   0.05   75.6805
00     4    50   20   0.10   76.4060
00     4   100   10   0.05   76.2349
00     4   100   10   0.10   79.2341
00     4   100   20   0.05   76.8338
00     4   100   20   0.10   78.8682
00     4   150   10   0.05   77.8778
00     4   150   10   0.10   80.3080
00     4   150   20   0.05   77.6668
00     4   150   20   0.10   79.9561
00     4   200   10   0.05   78.6827
00     4   200   10   0.10   80.8776
00     4   200   20   0.05   78.7359
00     4   200   20   0.10   81.0218
00     4   250   10   0.05   79.1968
00     4   250   10   0.10   80.9970
00     4   250   20   0.05   79.1791
00     4   250   20   0.10   81.2936
01     2    50   10   0.05   73.0790
01     2    50   10   0.10   73.6104
01     2    50   20   0.05   74.1309
01     2    50   20   0.10   74.3290
01     2   100   10   0.05   73.7196
01     2   100   10   0.10   75.1624
01     2   100   20   0.05   74.4855
01     2   100   20   0.10   74.7242
01     2   150   10   0.05   74.1223
01     2   150   10   0.10   75.4901
01     2   150   20   0.05   74.6099
01     2   150   20   0.10   75.1213
01     2   200   10   0.05   74.5911
01     2   200   10   0.10   76.1825
01     2   200   20   0.05   75.1288
01     2   200   20   0.10   75.9057
01     2   250   10   0.05   74.8417
01     2   250   10   0.10   76.6048
01     2   250   20   0.05   75.2519
01     2   250   20   0.10   75.8565
01     3    50   10   0.05   73.4489
01     3    50   10   0.10   73.7791
01     3    50   20   0.05   73.8266
01     3    50   20   0.10   74.5951
01     3   100   10   0.05   74.3129
01     3   100   10   0.10   75.1629
01     3   100   20   0.05   74.1279
01     3   100   20   0.10   75.2790
01     3   150   10   0.05   74.7218
01     3   150   10   0.10   75.7117
01     3   150   20   0.05   74.5404
01     3   150   20   0.10   75.8864
01     3   200   10   0.05   75.1185
01     3   200   10   0.10   76.1293
01     3   200   20   0.05   74.8195
01     3   200   20   0.10   76.1941
01     3   250   10   0.05   75.3592
01     3   250   10   0.10   76.3946
01     3   250   20   0.05   74.8748
01     3   250   20   0.10   76.6039
01     4    50   10   0.05   73.7395
01     4    50   10   0.10   73.9848
01     4    50   20   0.05   73.7236
01     4    50   20   0.10   73.9150
01     4   100   10   0.05   75.0193
01     4   100   10   0.10   74.7905
01     4   100   20   0.05   74.2251
01     4   100   20   0.10   75.0876
01     4   150   10   0.05   75.4507
01     4   150   10   0.10   75.4395
01     4   150   20   0.05   74.3740
01     4   150   20   0.10   75.5410
01     4   200   10   0.05   75.7251
01     4   200   10   0.10   75.9729
01     4   200   20   0.05   74.7334
01     4   200   20   0.10   75.9123
01     4   250   10   0.05   75.8750
01     4   250   10   0.10   76.1342
01     4   250   20   0.05   74.8579
01     4   250   20   0.10   76.2506
02     2    50   10   0.05   67.7545
02     2    50   10   0.10   68.3016
02     2    50   20   0.05   68.0372
02     2    50   20   0.10   68.5769
02     2   100   10   0.05   68.5070
02     2   100   10   0.10   69.5237
02     2   100   20   0.05   68.8839
02     2   100   20   0.10   70.3796
02     2   150   10   0.05   69.5306
02     2   150   10   0.10   70.1537
02     2   150   20   0.05   69.5051
02     2   150   20   0.10   71.5574
02     2   200   10   0.05   69.9479
02     2   200   10   0.10   70.9966
02     2   200   20   0.05   70.1797
02     2   200   20   0.10   72.4668
02     2   250   10   0.05   70.2846
02     2   250   10   0.10   71.6063
02     2   250   20   0.05   70.5044
02     2   250   20   0.10   72.6618
02     3    50   10   0.05   67.8147
02     3    50   10   0.10   68.7892
02     3    50   20   0.05   68.0083
02     3    50   20   0.10   69.7739
02     3   100   10   0.05   68.9628
02     3   100   10   0.10   70.3464
02     3   100   20   0.05   69.1854
02     3   100   20   0.10   71.5324
02     3   150   10   0.05   69.2564
02     3   150   10   0.10   71.1476
02     3   150   20   0.05   70.1538
02     3   150   20   0.10   72.7294
02     3   200   10   0.05   69.5636
02     3   200   10   0.10   71.8672
02     3   200   20   0.05   70.9735
02     3   200   20   0.10   73.2512
02     3   250   10   0.05   70.0189
02     3   250   10   0.10   72.2099
02     3   250   20   0.05   71.6306
02     3   250   20   0.10   73.9145
02     4    50   10   0.05   67.9166
02     4    50   10   0.10   69.2701
02     4    50   20   0.05   68.1559
02     4    50   20   0.10   69.9635
02     4   100   10   0.05   69.2293
02     4   100   10   0.10   70.9173
02     4   100   20   0.05   69.3328
02     4   100   20   0.10   71.9877
02     4   150   10   0.05   69.9397
02     4   150   10   0.10   71.5602
02     4   150   20   0.05   70.1899
02     4   150   20   0.10   72.9535
02     4   200   10   0.05   70.6181
02     4   200   10   0.10   72.1825
02     4   200   20   0.05   71.1057
02     4   200   20   0.10   73.6116
02     4   250   10   0.05   70.8942
02     4   250   10   0.10   72.3659
02     4   250   20   0.05   71.7188
02     4   250   20   0.10   74.2795
03     2    50   10   0.05   63.0170
03     2    50   10   0.10   63.4306
03     2    50   20   0.05   62.9149
03     2    50   20   0.10   63.3790
03     2   100   10   0.05   63.6770
03     2   100   10   0.10   64.7690
03     2   100   20   0.05   63.6107
03     2   100   20   0.10   64.2939
03     2   150   10   0.05   64.3873
03     2   150   10   0.10   65.3365
03     2   150   20   0.05   63.8914
03     2   150   20   0.10   64.8758
03     2   200   10   0.05   64.9271
03     2   200   10   0.10   65.7680
03     2   200   20   0.05   64.3976
03     2   200   20   0.10   65.7764
03     2   250   10   0.05   65.0436
03     2   250   10   0.10   66.0977
03     2   250   20   0.05   64.6630
03     2   250   20   0.10   66.3050
03     3    50   10   0.05   62.6272
03     3    50   10   0.10   63.1287
03     3    50   20   0.05   62.7058
03     3    50   20   0.10   63.1027
03     3   100   10   0.05   63.7207
03     3   100   10   0.10   64.6477
03     3   100   20   0.05   63.4178
03     3   100   20   0.10   64.6904
03     3   150   10   0.05   64.7422
03     3   150   10   0.10   65.6987
03     3   150   20   0.05   64.0405
03     3   150   20   0.10   65.8177
03     3   200   10   0.05   65.1248
03     3   200   10   0.10   66.0242
03     3   200   20   0.05   64.5841
03     3   200   20   0.10   66.4332
03     3   250   10   0.05   65.4652
03     3   250   10   0.10   66.5105
03     3   250   20   0.05   65.0521
03     3   250   20   0.10   67.2653
03     4    50   10   0.05   62.8651
03     4    50   10   0.10   64.2129
03     4    50   20   0.05   62.5441
03     4    50   20   0.10   63.7028
03     4   100   10   0.05   63.7424
03     4   100   10   0.10   65.9507
03     4   100   20   0.05   63.4084
03     4   100   20   0.10   65.5266
03     4   150   10   0.05   64.4650
03     4   150   10   0.10   66.8915
03     4   150   20   0.05   63.8570
03     4   150   20   0.10   66.2202
03     4   200   10   0.05   65.0187
03     4   200   10   0.10   67.3628
03     4   200   20   0.05   64.5369
03     4   200   20   0.10   66.9750
03     4   250   10   0.05   65.4085
03     4   250   10   0.10   67.8986
03     4   250   20   0.05   65.0347
03     4   250   20   0.10   67.5430
04     2    50   10   0.05   63.1865
04     2    50   10   0.10   63.5853
04     2    50   20   0.05   62.2225
04     2    50   20   0.10   62.6019
04     2   100   10   0.05   63.9718
04     2   100   10   0.10   65.1024
04     2   100   20   0.05   62.4419
04     2   100   20   0.10   63.6794
04     2   150   10   0.05   64.6568
04     2   150   10   0.10   66.0216
04     2   150   20   0.05   62.6158
04     2   150   20   0.10   64.3382
04     2   200   10   0.05   65.3549
04     2   200   10   0.10   66.9128
04     2   200   20   0.05   62.7331
04     2   200   20   0.10   64.9574
04     2   250   10   0.05   65.9073
04     2   250   10   0.10   67.2623
04     2   250   20   0.05   63.2103
04     2   250   20   0.10   65.6887
04     3    50   10   0.05   63.7491
04     3    50   10   0.10   64.6513
04     3    50   20   0.05   62.6579
04     3    50   20   0.10   63.1258
04     3   100   10   0.05   64.5414
04     3   100   10   0.10   66.3304
04     3   100   20   0.05   62.9284
04     3   100   20   0.10   64.2782
04     3   150   10   0.05   65.4394
04     3   150   10   0.10   67.1374
04     3   150   20   0.05   63.3401
04     3   150   20   0.10   65.1074
04     3   200   10   0.05   65.9636
04     3   200   10   0.10   67.7054
04     3   200   20   0.05   63.9246
04     3   200   20   0.10   65.7785
04     3   250   10   0.05   66.2706
04     3   250   10   0.10   67.8541
04     3   250   20   0.05   64.4382
04     3   250   20   0.10   66.2355
04     4    50   10   0.05   63.6830
04     4    50   10   0.10   65.2368
04     4    50   20   0.05   62.2669
04     4    50   20   0.10   63.1816
04     4   100   10   0.05   64.6532
04     4   100   10   0.10   66.9614
04     4   100   20   0.05   62.7909
04     4   100   20   0.10   64.1616
04     4   150   10   0.05   65.7050
04     4   150   10   0.10   67.8778
04     4   150   20   0.05   63.3020
04     4   150   20   0.10   64.7694
04     4   200   10   0.05   66.1873
04     4   200   10   0.10   68.1352
04     4   200   20   0.05   63.7061
04     4   200   20   0.10   65.2696
04     4   250   10   0.05   66.5771
04     4   250   10   0.10   68.4384
04     4   250   20   0.05   64.2350
04     4   250   20   0.10   65.6600
05     2    50   10   0.05   76.0678
05     2    50   10   0.10   76.8434
05     2    50   20   0.05   76.1037
05     2    50   20   0.10   76.8016
05     2   100   10   0.05   76.5358
05     2   100   10   0.10   77.4645
05     2   100   20   0.05   76.7157
05     2   100   20   0.10   78.0725
05     2   150   10   0.05   77.2242
05     2   150   10   0.10   78.7951
05     2   150   20   0.05   77.0225
05     2   150   20   0.10   79.3993
05     2   200   10   0.05   77.8299
05     2   200   10   0.10   79.8005
05     2   200   20   0.05   77.4970
05     2   200   20   0.10   79.8218
05     2   250   10   0.05   78.4003
05     2   250   10   0.10   80.6629
05     2   250   20   0.05   77.9856
05     2   250   20   0.10   81.0568
05     3    50   10   0.05   75.9637
05     3    50   10   0.10   77.0791
05     3    50   20   0.05   76.1394
05     3    50   20   0.10   76.8224
05     3   100   10   0.05   76.9371
05     3   100   10   0.10   77.9431
05     3   100   20   0.05   76.4193
05     3   100   20   0.10   78.3290
05     3   150   10   0.05   77.5934
05     3   150   10   0.10   79.2987
05     3   150   20   0.05   76.8786
05     3   150   20   0.10   79.2379
05     3   200   10   0.05   78.3513
05     3   200   10   0.10   79.8985
05     3   200   20   0.05   77.5191
05     3   200   20   0.10   80.2821
05     3   250   10   0.05   78.9559
05     3   250   10   0.10   80.8591
05     3   250   20   0.05   78.1241
05     3   250   20   0.10   80.7967
05     4    50   10   0.05   76.7905
05     4    50   10   0.10   77.4846
05     4    50   20   0.05   76.3343
05     4    50   20   0.10   77.3945
05     4   100   10   0.05   77.8730
05     4   100   10   0.10   78.5809
05     4   100   20   0.05   76.5086
05     4   100   20   0.10   78.8828
05     4   150   10   0.05   78.7022
05     4   150   10   0.10   79.6462
05     4   150   20   0.05   77.0660
05     4   150   20   0.10   80.2410
05     4   200   10   0.05   79.4262
05     4   200   10   0.10   80.2000
05     4   200   20   0.05   77.6493
05     4   200   20   0.10   81.4136
05     4   250   10   0.05   79.9752
05     4   250   10   0.10   80.5327
05     4   250   20   0.05   78.2112
05     4   250   20   0.10   81.8270
06     2    50   10   0.05  103.9332
06     2    50   10   0.10  103.7340
06     2    50   20   0.05  103.4416
06     2    50   20   0.10  103.8801
06     2   100   10   0.05  103.3823
06     2   100   10   0.10  103.8099
06     2   100   20   0.05  104.0183
06     2   100   20   0.10  104.8211
06     2   150   10   0.05  103.7465
06     2   150   10   0.10  106.3724
06     2   150   20   0.05  104.3082
06     2   150   20   0.10  105.7406
06     2   200   10   0.05  103.4300
06     2   200   10   0.10  106.7283
06     2   200   20   0.05  104.5033
06     2   200   20   0.10  106.8075
06     2   250   10   0.05  104.4262
06     2   250   10   0.10  107.6795
06     2   250   20   0.05  104.7939
06     2   250   20   0.10  107.4760
06     3    50   10   0.05  103.4117
06     3    50   10   0.10  103.7166
06     3    50   20   0.05  102.5641
06     3    50   20   0.10  104.2772
06     3   100   10   0.05  103.6917
06     3   100   10   0.10  104.8816
06     3   100   20   0.05  104.2127
06     3   100   20   0.10  106.2726
06     3   150   10   0.05  104.4600
06     3   150   10   0.10  106.4466
06     3   150   20   0.05  104.1995
06     3   150   20   0.10  106.9439
06     3   200   10   0.05  104.9568
06     3   200   10   0.10  106.6205
06     3   200   20   0.05  104.8703
06     3   200   20   0.10  108.1416
06     3   250   10   0.05  105.7780
06     3   250   10   0.10  107.7871
06     3   250   20   0.05  105.5735
06     3   250   20   0.10  108.8325
06     4    50   10   0.05  103.3680
06     4    50   10   0.10  102.8569
06     4    50   20   0.05  102.4009
06     4    50   20   0.10  103.9905
06     4   100   10   0.05  103.6224
06     4   100   10   0.10  103.5649
06     4   100   20   0.05  103.9234
06     4   100   20   0.10  105.7920
06     4   150   10   0.05  104.4771
06     4   150   10   0.10  104.3234
06     4   150   20   0.05  104.4137
06     4   150   20   0.10  106.9220
06     4   200   10   0.05  104.7736
06     4   200   10   0.10  104.4835
06     4   200   20   0.05  105.2657
06     4   200   20   0.10  108.4100
06     4   250   10   0.05  105.3722
06     4   250   10   0.10  104.8428
06     4   250   20   0.05  106.1165
06     4   250   20   0.10  109.2786
07     2    50   10   0.05  138.7939
07     2    50   10   0.10  141.7003
07     2    50   20   0.05  137.3492
07     2    50   20   0.10  139.1208
07     2   100   10   0.05  140.7856
07     2   100   10   0.10  144.7608
07     2   100   20   0.05  138.3194
07     2   100   20   0.10  142.7463
07     2   150   10   0.05  142.6530
07     2   150   10   0.10  147.9440
07     2   150   20   0.05  139.4712
07     2   150   20   0.10  144.8469
07     2   200   10   0.05  143.8948
07     2   200   10   0.10  149.2027
07     2   200   20   0.05  140.6106
07     2   200   20   0.10  146.2043
07     2   250   10   0.05  145.7256
07     2   250   10   0.10  150.8580
07     2   250   20   0.05  142.6396
07     2   250   20   0.10  147.5946
07     3    50   10   0.05  139.1649
07     3    50   10   0.10  144.2675
07     3    50   20   0.05  138.0760
07     3    50   20   0.10  140.9043
07     3   100   10   0.05  141.9289
07     3   100   10   0.10  149.1997
07     3   100   20   0.05  140.2085
07     3   100   20   0.10  142.8041
07     3   150   10   0.05  144.5432
07     3   150   10   0.10  152.0196
07     3   150   20   0.05  141.3886
07     3   150   20   0.10  145.2334
07     3   200   10   0.05  146.0242
07     3   200   10   0.10  152.5037
07     3   200   20   0.05  143.0183
07     3   200   20   0.10  146.5894
07     3   250   10   0.05  147.6306
07     3   250   10   0.10  153.5747
07     3   250   20   0.05  144.2977
07     3   250   20   0.10  148.4905
07     4    50   10   0.05  140.1450
07     4    50   10   0.10  143.8663
07     4    50   20   0.05  137.8929
07     4    50   20   0.10  140.4371
07     4   100   10   0.05  143.2726
07     4   100   10   0.10  146.4166
07     4   100   20   0.05  140.1287
07     4   100   20   0.10  143.7383
07     4   150   10   0.05  145.1617
07     4   150   10   0.10  148.7661
07     4   150   20   0.05  141.4067
07     4   150   20   0.10  145.3615
07     4   200   10   0.05  145.7382
07     4   200   10   0.10  149.3969
07     4   200   20   0.05  143.2657
07     4   200   20   0.10  146.9706
07     4   250   10   0.05  147.2530
07     4   250   10   0.10  150.1770
07     4   250   20   0.05  144.4936
07     4   250   20   0.10  148.0863
08     2    50   10   0.05  171.6795
08     2    50   10   0.10  171.7411
08     2    50   20   0.05  172.9079
08     2    50   20   0.10  173.9236
08     2   100   10   0.05  171.7757
08     2   100   10   0.10  169.5368
08     2   100   20   0.05  173.1691
08     2   100   20   0.10  173.6861
08     2   150   10   0.05  169.9136
08     2   150   10   0.10  170.1337
08     2   150   20   0.05  173.4538
08     2   150   20   0.10  174.0862
08     2   200   10   0.05  169.3925
08     2   200   10   0.10  170.5209
08     2   200   20   0.05  172.7674
08     2   200   20   0.10  174.7690
08     2   250   10   0.05  169.7225
08     2   250   10   0.10  171.4958
08     2   250   20   0.05  172.8917
08     2   250   20   0.10  176.0287
08     3    50   10   0.05  169.3947
08     3    50   10   0.10  170.8434
08     3    50   20   0.05  172.0628
08     3    50   20   0.10  173.0355
08     3   100   10   0.05  169.8203
08     3   100   10   0.10  172.3932
08     3   100   20   0.05  173.5179
08     3   100   20   0.10  173.8202
08     3   150   10   0.05  168.9394
08     3   150   10   0.10  173.8837
08     3   150   20   0.05  173.6758
08     3   150   20   0.10  174.3813
08     3   200   10   0.05  169.2505
08     3   200   10   0.10  174.6269
08     3   200   20   0.05  173.9457
08     3   200   20   0.10  175.8029
08     3   250   10   0.05  169.6695
08     3   250   10   0.10  175.2955
08     3   250   20   0.05  174.7425
08     3   250   20   0.10  177.6551
08     4    50   10   0.05  169.7381
08     4    50   10   0.10  171.0734
08     4    50   20   0.05  171.5310
08     4    50   20   0.10  173.4107
08     4   100   10   0.05  168.6362
08     4   100   10   0.10  173.1284
08     4   100   20   0.05  172.8505
08     4   100   20   0.10  175.9202
08     4   150   10   0.05  169.4192
08     4   150   10   0.10  174.6954
08     4   150   20   0.05  172.7221
08     4   150   20   0.10  176.4183
08     4   200   10   0.05  169.2064
08     4   200   10   0.10  175.5698
08     4   200   20   0.05  173.5989
08     4   200   20   0.10  177.7161
08     4   250   10   0.05  170.1114
08     4   250   10   0.10  176.1672

In [127]:
lin_xgb_results_df = pd.DataFrame(lin_xgb_results)

rmse_by_hour = lin_xgb_results_df.pivot_table(
    index=["max_depth", "n_estimators", "min_child_weight", "learning_rate"],
    columns="hour",
    values="mean_rmse"
).reset_index()

best_per_hour_lin_xgb = lin_xgb_results_df.loc[lin_xgb_results_df.groupby("hour")["mean_rmse"].idxmin()].reset_index(drop=True)

In [128]:
best_per_hour_lin_xgb

    hour  max_depth  n_estimators  min_child_weight  learning_rate   mean_rmse
0      0          4            50                10           0.05   74.239318
1      1          2            50                10           0.05   73.079033
2      2          2            50                10           0.05   67.754544
3      3          4            50                20           0.05   62.544141
4      4          2            50                20           0.05   62.222497
5      5          3            50                10           0.05   75.963719
6      6          4            50                20           0.05  102.400875
7      7          2            50                20           0.05  137.349189
8      8          4           100                10           0.05  168.636245
9      9          2           200                10           0.05  200.513561
10    10          4           100                20           0.05  204.875754
11    11          2           150                10           0.10  213.940081
12    12          4           150                10           0.05  217.088121
13    13          3            50                10           0.10  218.929193
14    14          4            50                10           0.05  218.489460
15    15          4           150                10           0.05  198.939062
16    16          4            50                10           0.05  177.824558
17    17          4            50                10           0.05  146.567441
18    18          4            50                20           0.05  131.425082
19    19          2            50                20           0.05  113.872675
20    20          2            50                20           0.05  100.033434
21    21          2            50                20           0.05   86.808268
22    22          2            50                10           0.05   79.079134
23    23          4            50                10           0.05   73.064750

In [131]:
best_per_hour_hyperparams = best_per_hour_lin_xgb[["max_depth", "n_estimators", "min_child_weight", "learning_rate"]]
best_at_max_hour_hyperparams = best_per_hour_lin_xgb.loc[best_per_hour_lin_xgb["mean_rmse"].idxmax()].to_frame().T

best_per_hour_hyperparams.to_csv("../src/models/best_per_hour_lin_xgb_hyperparams.csv", index=False)
best_at_max_hour_hyperparams.to_csv("../src/models/best_max_hour_lin_xgb_hyperparams.csv", index=False)